spring.application.name=WoocommerceIntegration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/WoocommerceIntegration
spring.datasource.username=postgres
spring.datasource.password=istifano
spring.jpa.hibernate.ddl-auto=update


# Configuration WooCommerce statique
woocommerce.app.name=DASHY
woocommerce.scope=read_write
woocommerce.return.url=http://localhost:4200/produits
woocommerce.callback.url=https://70cbfc41dbf5.ngrok-free.app/callback


woocommerce.user.id.prefix=USER_
#woocommerce.store.url=https://mintcream-ostrich-169234.hostingersite.com
server.port=8080












spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect